### ISSUE TITLE
Error 500 - Internal Server Error

### ISSUE THREAD

**Issue by dima1002** [eryx12o45/grommunio-web-google2fa-plugin#1]
After logging into a mailbox we immediately get 
"Error 500 - Internal Server Error". 
The 500 (Internal Server Error) status code indicates that the server encountered an unexpected condition that prevented it from fulfilling the request.

What could that be?

Where can you tell each user individually whether it is activated or not?

**Comment by eryx12o45** [comment]
You can activate or deactivate the Plugin in the settings of each user. Did you have a look at the nginx and or php-fpm logs regarding the 500 error?

How did you "install" the Plugin? I will update the README.md on how to install the Plugin later. Please retry with this again.

**Comment by dima1002** [comment]
We have copied the dates just in the folder:

/usr/share/grommunio-web/plugins
drwxr-xr-x 5 root root 182 Nov 12 13:04 grommunio-web-google2fa

grom:/usr/share/grommunio-web/plugins/grommunio-web-google2fa # ls -ahltr
total 64K
-rw-r--r-- 1 root root 795 Nov 12 13:04 README.md
drwxr-xr-x 3 root root 197 Nov 12 13:04 php
-rw-r--r-- 1 root root 42K Nov 12 13:04 package-lock.json
-rw-r--r-- 1 root root 260 Nov 12 13:04 package.json
-rw-r--r-- 1 root root 1.6K Nov 12 13:04 manifest.xml
-rw-r--r-- 1 root root 1.4K Nov 12 13:04 Makefile
drwxr-xr-x 4 root root 60 Nov 12 13:04 js
- rw - r - - r -- 1 root root 736 Nov 12 13:04 config.php.org
lrwxrwxrwx 1 root root 33 Nov 12 1:04 PM config.php -> /etc/grommunio-web/config-2fa.php
drwxr-xr-x 14 root root 211 Nov 12 13:04 .
drwxr-xr-x 4 root root 30 Nov 12 13:04 resources
drwxr-xr-x 5 root root 182 Nov 12 13:04 .
grom:/usr/share/grommunio-web/plugins/grommunio-web-google2fa#


Logging:
 [12-Nov-2024 13:07:25] WARNING: [pool grommunio-web-pool] child 1522 said into stderr: "NOTICE: PHP message: grommunio Web user: test@test.com: authentication failure at MAPI"
[12-Nov-2024 13:07:29] WARNING: [pool grommunio-web-pool] child 1523 said into stderr: "NOTICE: PHP message: grommunio Web user: test@test.com: authentication failure at MAPI"
[12-Nov-2024 13:07:37] WARNING: [pool grommunio-web-pool] child 1521 said into stderr: "NOTICE: PHP message: grommunio Web user: test@test.com: authentication failure at MAPI"

Unfortunately I can't even log in to activate or deactivate the plugin.

If I delete the plugin from the folder, I can log in again immediately.

**Comment by eryx12o45** [comment]
Please have a look at the updated README.md file and let me know if this fixes the problem :-)

**Comment by dima1002** [comment]
After the reboot, there is still exactly the same error with 500 and the log says nothing different than before.

I have logged the whole process here, including the Grommunio version, etc.

[2fa.txt](https://github.com/user-attachments/files/17717679/2fa.txt)

**Comment by eryx12o45** [comment]
That looks all good. I deleted the plugin again from my machine and build it from repo and it works (there was a small issue which deactivated all options), but that has nothing to do with the 500 error.

Which PHP version do you have installed. As I am using the plugin on a Debian 12 machine with PHP 8.2

**Comment by dima1002** [comment]
we have the original ISO. Then it's the PHP version. The only question is whether we can update to 8.2?

grom:/usr/share/grommunio-web/plugins # cat /etc/os-release
NAME="grommunio"
VERSION="2023.11.3"
ID="grommunio-lds"
ID_LIKE="suse"
VERSION_ID="2023.11.3"
PRETTY_NAME="grommunio"
ANSI_COLOR="0;36"
HOME_URL="https://grommunio.com/"
DOCUMENTATION_URL="https://docs.grommunio.com/"
grom:/usr/share/grommunio-web/plugins # php -v
PHP 8.0.30 (cli) (built: Oct 11 2024 12:00:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.30, Copyright (c) Zend Technologies
grom:/usr/share/grommunio-web/plugins # rpm -qa | grep php
php8-ctype-8.0.30-150400.4.46.1.x86_64
php8-pcntl-8.0.30-150400.4.46.1.x86_64
php8-zip-8.0.30-150400.4.46.1.x86_64
php8-APCu-5.1.22-bp155.2.3.1.x86_64
php8-redis-5.3.7-lp155.1.9.x86_64
php8-curl-8.0.30-150400.4.46.1.x86_64
php8-intl-8.0.30-150400.4.46.1.x86_64
php8-pdo-8.0.30-150400.4.46.1.x86_64
php8-sysvshm-8.0.30-150400.4.46.1.x86_64
php8-zlib-8.0.30-150400.4.46.1.x86_64
php8-sqlite-8.0.30-150400.4.46.1.x86_64
php8-fpm-8.0.30-150400.4.46.1.x86_64
php8-gd-8.0.30-150400.4.46.1.x86_64
php8-mbstring-8.0.30-150400.4.46.1.x86_64
php8-posix-8.0.30-150400.4.46.1.x86_64
php8-xmlreader-8.0.30-150400.4.46.1.x86_64
php8-mysql-8.0.30-150400.4.46.1.x86_64
php8-cli-8.0.30-150400.4.46.1.x86_64
php8-8.0.30-150400.4.46.1.x86_64
php8-bcmath-8.0.30-150400.4.46.1.x86_64
php8-gettext-8.0.30-150400.4.46.1.x86_64
php8-openssl-8.0.30-150400.4.46.1.x86_64
php8-soap-8.0.30-150400.4.46.1.x86_64
php8-xmlwriter-8.0.30-150400.4.46.1.x86_64
mapi-header-php-1.4.0.db15bd0-lp155.16.1.noarch
php8-iconv-8.0.30-150400.4.46.1.x86_64
php8-sodium-8.0.30-150400.4.46.1.x86_64
php8-dom-8.0.30-150400.4.46.1.x86_64
grom:/usr/share/grommunio-web/plugins #

**Comment by dima1002** [comment]
You can probably update Suse to 15.6, which includes PHP 8.2. I'll check it and get back to you.

**Comment by eryx12o45** [comment]
Thx for the info and sorry for this. I am not using the standard appliance / installation (not a SuSE fan ^_^)

**Comment by dima1002** [comment]
The update from Suse 15.5 to 15.6 worked and we now have PHP 8.2.
By the way, I don't like Suse either :-) it was just the standard ISO back then
I could then see the module in the settings. I was able to activate the plugin. However, all the settings were grayed out. See screenshot.

I now have the problem that I did tests on the settings.

grom:/usr/share/grommunio-web/plugins/google2fa/config.php

![2FA](https://github.com/user-attachments/assets/3285db8f-e1b8-4ba3-8092-9e03cb2d2b3c)

Now I can no longer access the system with a user because 2FA is activated. Can I deactivate it again in the console?
in the config.php is set to true, false, false, false

**Comment by eryx12o45** [comment]
Ah, good question. I hadn't tried this :-( I will need to look into this tomorrow. Sorry. It could help to set the first value also to false, because this disables the "AUTO ENABLE" for all users. (or at least it should).

**Comment by eryx12o45** [comment]
You can also please update the git checkout and rebuild the plugin. I've fixed the greyed out settings earlier :-)

**Comment by dima1002** [comment]
thank you :-)  unfortunately I get an error when compiling

rom:~/NEU # git clone https://github.com/eryx12o45/grommunio-web-google2fa-plugin.git
Klone nach 'grommunio-web-google2fa-plugin'...
remote: Enumerating objects: 129, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 129 (delta 32), reused 120 (delta 26), pack-reused 0 (from 0)
Empfange Objekte: 100% (129/129), 79.84 KiB | 5.70 MiB/s, fertig.
Löse Unterschiede auf: 100% (32/32), fertig.
grom:~/NEU # cd grommunio-web-google2fa-plugin
grom:~/NEU/grommunio-web-google2fa-plugin # make DESTDIR=./google2fa
mkdir -p $(dirname google2fa/manifest.xml)
cp manifest.xml google2fa/manifest.xml
mkdir -p $(dirname google2fa/config.php)
cp config.php google2fa/config.php
mkdir -p $(dirname google2fa/resources/css/google2fa.css)
cp resources/css/google2fa.css google2fa/resources/css/google2fa.css
mkdir -p $(dirname google2fa/resources/icons/google2fa_icon_category.png)
cp resources/icons/google2fa_icon_category.png google2fa/resources/icons/google2fa_icon_category.png
mkdir -p $(dirname google2fa/resources/icons/google2fa_icon_category_large.png)
cp resources/icons/google2fa_icon_category_large.png google2fa/resources/icons/google2fa_icon_category_large.png
mkdir -p $(dirname google2fa/php/class.google2fadata.settings.php)
cp php/class.google2fadata.settings.php google2fa/php/class.google2fadata.settings.php
mkdir -p $(dirname google2fa/php/class.google2famodule.php)
cp php/class.google2famodule.php google2fa/php/class.google2famodule.php
mkdir -p $(dirname google2fa/php/composer.json)
cp php/composer.json google2fa/php/composer.json
mkdir -p $(dirname google2fa/php/composer.lock)
cp php/composer.lock google2fa/php/composer.lock
mkdir -p $(dirname google2fa/php/login.php)
cp php/login.php google2fa/php/login.php
mkdir -p $(dirname google2fa/php/logon.php)
cp php/logon.php google2fa/php/logon.php
mkdir -p $(dirname google2fa/php/plugin.google2fa.php)
cp php/plugin.google2fa.php google2fa/php/plugin.google2fa.php
mkdir -p $(dirname google2fa/php/vendor/autoload.php)
cp php/vendor/autoload.php google2fa/php/vendor/autoload.php
mkdir -p $(dirname google2fa/php/vendor/composer/ClassLoader.php)
cp php/vendor/composer/ClassLoader.php google2fa/php/vendor/composer/ClassLoader.php
mkdir -p $(dirname google2fa/php/vendor/composer/InstalledVersions.php)
cp php/vendor/composer/InstalledVersions.php google2fa/php/vendor/composer/InstalledVersions.php
mkdir -p $(dirname google2fa/php/vendor/composer/LICENSE)
cp php/vendor/composer/LICENSE google2fa/php/vendor/composer/LICENSE
mkdir -p $(dirname google2fa/php/vendor/composer/autoload_classmap.php)
cp php/vendor/composer/autoload_classmap.php google2fa/php/vendor/composer/autoload_classmap.php
mkdir -p $(dirname google2fa/php/vendor/composer/autoload_files.php)
cp php/vendor/composer/autoload_files.php google2fa/php/vendor/composer/autoload_files.php
mkdir -p $(dirname google2fa/php/vendor/composer/autoload_namespaces.php)
cp php/vendor/composer/autoload_namespaces.php google2fa/php/vendor/composer/autoload_namespaces.php
mkdir -p $(dirname google2fa/php/vendor/composer/autoload_psr4.php)
cp php/vendor/composer/autoload_psr4.php google2fa/php/vendor/composer/autoload_psr4.php
mkdir -p $(dirname google2fa/php/vendor/composer/autoload_real.php)
cp php/vendor/composer/autoload_real.php google2fa/php/vendor/composer/autoload_real.php
mkdir -p $(dirname google2fa/php/vendor/composer/autoload_static.php)
cp php/vendor/composer/autoload_static.php google2fa/php/vendor/composer/autoload_static.php
mkdir -p $(dirname google2fa/php/vendor/composer/installed.json)
cp php/vendor/composer/installed.json google2fa/php/vendor/composer/installed.json
mkdir -p $(dirname google2fa/php/vendor/composer/installed.php)
cp php/vendor/composer/installed.php google2fa/php/vendor/composer/installed.php
mkdir -p $(dirname google2fa/php/vendor/composer/platform_check.php)
cp php/vendor/composer/platform_check.php google2fa/php/vendor/composer/platform_check.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/LICENSE.txt)
cp php/vendor/paragonie/constant_time_encoding/LICENSE.txt google2fa/php/vendor/paragonie/constant_time_encoding/LICENSE.txt
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/README.md)
cp php/vendor/paragonie/constant_time_encoding/README.md google2fa/php/vendor/paragonie/constant_time_encoding/README.md
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/composer.json)
cp php/vendor/paragonie/constant_time_encoding/composer.json google2fa/php/vendor/paragonie/constant_time_encoding/composer.json
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/Base32.php)
cp php/vendor/paragonie/constant_time_encoding/src/Base32.php google2fa/php/vendor/paragonie/constant_time_encoding/src/Base32.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/Base32Hex.php)
cp php/vendor/paragonie/constant_time_encoding/src/Base32Hex.php google2fa/php/vendor/paragonie/constant_time_encoding/src/Base32Hex.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/Base64.php)
cp php/vendor/paragonie/constant_time_encoding/src/Base64.php google2fa/php/vendor/paragonie/constant_time_encoding/src/Base64.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/Base64DotSlash.php)
cp php/vendor/paragonie/constant_time_encoding/src/Base64DotSlash.php google2fa/php/vendor/paragonie/constant_time_encoding/src/Base64DotSlash.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/Base64DotSlashOrdered.php)
cp php/vendor/paragonie/constant_time_encoding/src/Base64DotSlashOrdered.php google2fa/php/vendor/paragonie/constant_time_encoding/src/Base64DotSlashOrdered.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/Base64UrlSafe.php)
cp php/vendor/paragonie/constant_time_encoding/src/Base64UrlSafe.php google2fa/php/vendor/paragonie/constant_time_encoding/src/Base64UrlSafe.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/Binary.php)
cp php/vendor/paragonie/constant_time_encoding/src/Binary.php google2fa/php/vendor/paragonie/constant_time_encoding/src/Binary.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/EncoderInterface.php)
cp php/vendor/paragonie/constant_time_encoding/src/EncoderInterface.php google2fa/php/vendor/paragonie/constant_time_encoding/src/EncoderInterface.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/Encoding.php)
cp php/vendor/paragonie/constant_time_encoding/src/Encoding.php google2fa/php/vendor/paragonie/constant_time_encoding/src/Encoding.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/Hex.php)
cp php/vendor/paragonie/constant_time_encoding/src/Hex.php google2fa/php/vendor/paragonie/constant_time_encoding/src/Hex.php
mkdir -p $(dirname google2fa/php/vendor/paragonie/constant_time_encoding/src/RFC4648.php)
cp php/vendor/paragonie/constant_time_encoding/src/RFC4648.php google2fa/php/vendor/paragonie/constant_time_encoding/src/RFC4648.php
mkdir -p $(dirname google2fa/php/vendor/psr/clock/CHANGELOG.md)
cp php/vendor/psr/clock/CHANGELOG.md google2fa/php/vendor/psr/clock/CHANGELOG.md
mkdir -p $(dirname google2fa/php/vendor/psr/clock/LICENSE)
cp php/vendor/psr/clock/LICENSE google2fa/php/vendor/psr/clock/LICENSE
mkdir -p $(dirname google2fa/php/vendor/psr/clock/README.md)
cp php/vendor/psr/clock/README.md google2fa/php/vendor/psr/clock/README.md
mkdir -p $(dirname google2fa/php/vendor/psr/clock/composer.json)
cp php/vendor/psr/clock/composer.json google2fa/php/vendor/psr/clock/composer.json
mkdir -p $(dirname google2fa/php/vendor/psr/clock/src/ClockInterface.php)
cp php/vendor/psr/clock/src/ClockInterface.php google2fa/php/vendor/psr/clock/src/ClockInterface.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/LICENSE)
cp php/vendor/spomky-labs/otphp/LICENSE google2fa/php/vendor/spomky-labs/otphp/LICENSE
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/README.md)
cp php/vendor/spomky-labs/otphp/README.md google2fa/php/vendor/spomky-labs/otphp/README.md
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/SECURITY.md)
cp php/vendor/spomky-labs/otphp/SECURITY.md google2fa/php/vendor/spomky-labs/otphp/SECURITY.md
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/composer.json)
cp php/vendor/spomky-labs/otphp/composer.json google2fa/php/vendor/spomky-labs/otphp/composer.json
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/Factory.php)
cp php/vendor/spomky-labs/otphp/src/Factory.php google2fa/php/vendor/spomky-labs/otphp/src/Factory.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/FactoryInterface.php)
cp php/vendor/spomky-labs/otphp/src/FactoryInterface.php google2fa/php/vendor/spomky-labs/otphp/src/FactoryInterface.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/HOTP.php)
cp php/vendor/spomky-labs/otphp/src/HOTP.php google2fa/php/vendor/spomky-labs/otphp/src/HOTP.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/HOTPInterface.php)
cp php/vendor/spomky-labs/otphp/src/HOTPInterface.php google2fa/php/vendor/spomky-labs/otphp/src/HOTPInterface.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/InternalClock.php)
cp php/vendor/spomky-labs/otphp/src/InternalClock.php google2fa/php/vendor/spomky-labs/otphp/src/InternalClock.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/OTP.php)
cp php/vendor/spomky-labs/otphp/src/OTP.php google2fa/php/vendor/spomky-labs/otphp/src/OTP.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/OTPInterface.php)
cp php/vendor/spomky-labs/otphp/src/OTPInterface.php google2fa/php/vendor/spomky-labs/otphp/src/OTPInterface.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/ParameterTrait.php)
cp php/vendor/spomky-labs/otphp/src/ParameterTrait.php google2fa/php/vendor/spomky-labs/otphp/src/ParameterTrait.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/TOTP.php)
cp php/vendor/spomky-labs/otphp/src/TOTP.php google2fa/php/vendor/spomky-labs/otphp/src/TOTP.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/TOTPInterface.php)
cp php/vendor/spomky-labs/otphp/src/TOTPInterface.php google2fa/php/vendor/spomky-labs/otphp/src/TOTPInterface.php
mkdir -p $(dirname google2fa/php/vendor/spomky-labs/otphp/src/Url.php)
cp php/vendor/spomky-labs/otphp/src/Url.php google2fa/php/vendor/spomky-labs/otphp/src/Url.php
mkdir -p $(dirname google2fa/php/vendor/symfony/deprecation-contracts/CHANGELOG.md)
cp php/vendor/symfony/deprecation-contracts/CHANGELOG.md google2fa/php/vendor/symfony/deprecation-contracts/CHANGELOG.md
mkdir -p $(dirname google2fa/php/vendor/symfony/deprecation-contracts/LICENSE)
cp php/vendor/symfony/deprecation-contracts/LICENSE google2fa/php/vendor/symfony/deprecation-contracts/LICENSE
mkdir -p $(dirname google2fa/php/vendor/symfony/deprecation-contracts/README.md)
cp php/vendor/symfony/deprecation-contracts/README.md google2fa/php/vendor/symfony/deprecation-contracts/README.md
mkdir -p $(dirname google2fa/php/vendor/symfony/deprecation-contracts/composer.json)
cp php/vendor/symfony/deprecation-contracts/composer.json google2fa/php/vendor/symfony/deprecation-contracts/composer.json
mkdir -p $(dirname google2fa/php/vendor/symfony/deprecation-contracts/function.php)
cp php/vendor/symfony/deprecation-contracts/function.php google2fa/php/vendor/symfony/deprecation-contracts/function.php
mkdir -p ./google2fa/js
cat js/Google2FAPlugin.js js/data/Configuration.js js/data/ResponseHandler.js js/settings/Category.js js/settings/GeneralSettingsWidget.js > google2fa/js/google2fa-debug.js
./node_modules/terser/bin/terser google2fa/js/google2fa-debug.js --output google2fa/js/google2fa.js \
        --source-map "url='google2fa.js.map'" \
        --mangle reserved=['FormData','Ext','Zarafa','container','settings','properties','languages','serverconfig','user','version','urlActionData','console','Tokenizr','module','define','global','require','proxy','_','dgettext','dngettext','dnpgettext','ngettext','pgettext','onResize','tinymce','resizeLoginBox','userManager','DOMPurify','PDFJS','odf','L','GeoSearch'] --compress ecma=2015,computed_props=false
/bin/sh: ./node_modules/terser/bin/terser: No such file or directory
make: *** [Makefile:31: google2fa/js/google2fa.js] Error 127
grom:~/NEU/grommunio-web-google2fa-plugin #

**Comment by eryx12o45** [comment]
you again need to execute "npm install" this should install the missing tenser dependency

**Comment by dima1002** [comment]
npm is installed
grom:/usr/share/grommunio-web/plugins # npm -v
10.7.0

**Comment by eryx12o45** [comment]
Yes but you have to execute „npm install“ in the plugin folder itself. this doesn’t install npm but tenser which is missing according to the log

**Comment by dima1002** [comment]
OK, it works now.
But it seems that you really have to delete the cache every time you make a change. So activate the plugin, delete the cache, scan the CR code and enter the code, delete the cache, etc. Only then did it work.
The code works in Chrome, but in Edge and Safari, after scanning the QR code, I only got the code 000000
But with Chrome and deleting the cache, it works for me now. Thanks

**Comment by eryx12o45** [comment]
Puh ok good to know. I only tested with Chrome, Brave and Safari so far. But actually didn't have to delete the cache. Thanks for the info I hope overall the plugin will help you nevertheless
